using Jtodo.Domains;
using Jtodo.DTOs;
using Jtodo.Mappers;
using Jtodo.Values;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Jtodo.Interfaces;

namespace Jtodo.Services
{
    public class TodoListService
    {
        private readonly IAppUnit _unitOfWork;

        public TodoListService(IAppUnit unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public async Task<List<TodoListDto>> Get_All_Todo_list_Async()
        {
            var domains = await _unitOfWork.TodoListRepository.Get_All_Todo_list_Async();
            return domains.ToDtoList();
        }

        public async Task<TodoListDto?> Get_Todo_List_Async(ulong id)
        {
            var domain = await _unitOfWork.TodoListRepository.Get_Todo_List_Async(id);
            return domain?.ToDto();
        }

        public async Task<ulong> Create_Todo_List_Async(TodoListDto dto)
        {
            var domain = dto.ToDomain();
            await _unitOfWork.TodoListRepository.Add_Todo_List_Async(domain);
            await _unitOfWork.SaveChangesAsync();
            return domain.Id;
        }

        public async Task Update_Todo_List_Async(TodoListDto dto)
        {
            var domain = dto.ToDomain();
            await _unitOfWork.TodoListRepository.Update_Todo_List_Async(domain);
            await _unitOfWork.SaveChangesAsync();
        }

        public async Task Delete_Todo_List_Async(ulong id)
        {
            await _unitOfWork.TodoListRepository.Delete_Todo_List_Async(id);
            await _unitOfWork.SaveChangesAsync();
        }

        public async Task Delete_TodoList_Complete_Async(ulong id)
        {
            await _unitOfWork.TodoListRepository.Delete_Todo_List_With_Items_Async(id);
            await _unitOfWork.SaveChangesAsync();
        }

        public async Task<TodoItemDto> CreateTaskInListAsync(ulong todoListId)
        {
            try
            {
                // Get the first available type (or default to 1 if no types exist)
                var types = await _unitOfWork.TypeRepository.GetAllTypesAsync();
                ulong defaultTypeId = types.FirstOrDefault()?.Id ?? 1;

                // Create new TodoItem with default values
                var newTodoItem = new TodoItem(
                    Id: 0, // Auto-generated by database
                    Title: "New Task",
                    Description: "",
                    StartDate: DateTime.Now,
                    DueDate: DateTime.Now.AddDays(7),
                    Priority: Priority.Medium,
                    Status: Status.Pending,
                    TypeId: defaultTypeId
                );

                // Add TodoItem to database
                await _unitOfWork.TodoItemRepository.AddTodoItemAsync(newTodoItem);
                await _unitOfWork.SaveChangesAsync();

                // Create junction record to link TodoItem with TodoList
                await _unitOfWork.TodoListRepository.Add_TodoItem_To_TodoList_Async(todoListId, newTodoItem.Id);
                await _unitOfWork.SaveChangesAsync();

                Console.WriteLine($"[INFO] Successfully created new task ID: {newTodoItem.Id} in TodoList ID: {todoListId}");

                // Convert to DTO and return
                return newTodoItem.ToDto();
            }
            catch (Exception ex)
            {
                Console.WriteLine($"[ERROR] Failed to create task in list: {ex.Message}");
                throw;
            }
        }
    }
}

