using Jtodo.Domains;
using Jtodo.DTOs;
using Jtodo.Mappers;
using Jtodo.Values;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Jtodo.Interfaces;

namespace Jtodo.Services
{
    public class TodoListService
    {
        private readonly IAppUnit _unitOfWork;

        // Event for notifying when data changes
        public event EventHandler? DataChanged;

        public TodoListService(IAppUnit unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        // Method to trigger the event
        protected virtual void OnDataChanged()
        {
            DataChanged?.Invoke(this, EventArgs.Empty);
        }

        public async Task<List<TodoListDto>> Get_All_Todo_list_Async()
        {
            var domains = await _unitOfWork.TodoListRepository.Get_All_Todo_list_Async();
            return domains.ToDtoList();
        }

        public async Task<TodoListDto?> Get_Todo_List_Async(ulong id)
        {
            var domain = await _unitOfWork.TodoListRepository.Get_Todo_List_Async(id);
            return domain?.ToDto();
        }

        public async Task<ulong> Create_Todo_List_Async(TodoListDto dto)
        {
            var domain = dto.ToDomain();
            await _unitOfWork.TodoListRepository.Add_Todo_List_Async(domain);
            await _unitOfWork.SaveChangesAsync();
            return domain.Id;
        }

        public async Task Update_Todo_List_Async(TodoListDto dto)
        {
            var domain = dto.ToDomain();
            await _unitOfWork.TodoListRepository.Update_Todo_List_Async(domain);
            await _unitOfWork.SaveChangesAsync();
        }

        public async Task Delete_Todo_List_Async(ulong id)
        {
            await _unitOfWork.TodoListRepository.Delete_Todo_List_Async(id);
            await _unitOfWork.SaveChangesAsync();
            
            OnDataChanged(); // Notify subscribers
        }

        public async Task Delete_TodoList_Complete_Async(ulong id)
        {
            await _unitOfWork.TodoListRepository.Delete_Todo_List_With_Items_Async(id);
            await _unitOfWork.SaveChangesAsync();
            
            OnDataChanged(); // Notify subscribers
        }

        public async Task<TodoItemDto> CreateTaskInListAsync(ulong todoListId)
        {
            try
            {
                // Get "None" type ID as default
                var types = await _unitOfWork.TypeRepository.GetAllTypesAsync();
                var noneType = types.FirstOrDefault(t => t.Text == "None");
                ulong defaultTypeId;

                if (noneType == null)
                {
                    // Ensure "None" type exists
                    var dbContext = _unitOfWork.GetDbContext();
                    await dbContext.EnsureDefaultTypeExistsAsync();
                    
                    // Retrieve again
                    types = await _unitOfWork.TypeRepository.GetAllTypesAsync();
                    noneType = types.FirstOrDefault(t => t.Text == "None");
                    defaultTypeId = noneType?.Id ?? types.FirstOrDefault()?.Id ?? 1;
                }
                else
                {
                    defaultTypeId = noneType.Id;
                }

                // Create new TodoItem with default values
                var newTodoItem = new TodoItem(
                    Id: 0, // Auto-generated by database
                    Title: "New Task",
                    Description: "",
                    StartDate: DateTime.Now,
                    DueDate: DateTime.Now.AddDays(7),
                    Priority: Priority.Medium,
                    Status: Status.Pending,
                    TypeId: defaultTypeId
                );

                // Add TodoItem to database
                await _unitOfWork.TodoItemRepository.AddTodoItemAsync(newTodoItem);
                await _unitOfWork.SaveChangesAsync();

                // Create junction record to link TodoItem with TodoList
                await _unitOfWork.TodoListRepository.Add_TodoItem_To_TodoList_Async(todoListId, newTodoItem.Id);
                await _unitOfWork.SaveChangesAsync();

                Console.WriteLine($"[INFO] Successfully created new task ID: {newTodoItem.Id} in TodoList ID: {todoListId}");

                OnDataChanged(); // Notify subscribers

                // Convert to DTO and return
                return newTodoItem.ToDto();
            }
            catch (Exception ex)
            {
                Console.WriteLine($"[ERROR] Failed to create task in list: {ex.Message}");
                throw;
            }
        }

        public async Task<List<TodoItemDto>> GetUpcomingTasksAsync(int daysAhead = 3)
        {
            try
            {
                var allItems = await _unitOfWork.TodoItemRepository.GetAllTodoItemsAsync();
                var today = DateTime.Now.Date;
                var endDate = today.AddDays(daysAhead);

                var upcomingTasks = allItems
                    .Where(item => item.DueDate.HasValue && 
                                   item.DueDate.Value.Date >= today && 
                                   item.DueDate.Value.Date <= endDate &&
                                   item.Status != Status.Completed &&
                                   item.Status != Status.Cancelled)
                    .OrderBy(item => item.DueDate)
                    .Select(item => item.ToDto())
                    .ToList();

                return upcomingTasks;
            }
            catch (Exception ex)
            {
                Console.WriteLine($"[ERROR] Failed to get upcoming tasks: {ex.Message}");
                return new List<TodoItemDto>();
            }
        }

        public async Task<List<UpcomingTaskDto>> GetUpcomingTasksWithDetailsAsync(int daysAhead = 3)
        {
            try
            {
                var today = DateTime.Now.Date;
                var tomorrow = today.AddDays(1);
                var endDate = today.AddDays(daysAhead);

                // Get all TodoLists with their items
                var allTodoLists = await _unitOfWork.TodoListRepository.Get_All_Todo_list_Async();
                
                // Flatten the data and create UpcomingTaskDto
                var upcomingTasks = allTodoLists
                    .SelectMany(list => list.Todo_Items
                        .Where(item => item.DueDate.HasValue &&
                                       item.DueDate.Value.Date >= tomorrow && // Changed from today to tomorrow (1-3 days)
                                       item.DueDate.Value.Date <= endDate &&
                                       item.Status != Status.Completed &&
                                       item.Status != Status.Cancelled)
                        .Select(item =>
                        {
                            var dueDate = item.DueDate ?? DateTime.Now;
                            var daysRemaining = (dueDate.Date - today).Days;
                            
                            return new UpcomingTaskDto
                            {
                                TaskTitle = item.Title,
                                ListName = list.Title,
                                DueDate = dueDate,
                                DaysRemaining = daysRemaining,
                                DueDateText = FormatDueDate(dueDate),
                                UrgencyColor = GetUrgencyColor(daysRemaining)
                            };
                        }))
                    .OrderBy(task => task.DueDate) // Order by date (nearest first)
                    .ToList();

                return upcomingTasks;
            }
            catch (Exception ex)
            {
                Console.WriteLine($"[ERROR] Failed to get upcoming tasks with details: {ex.Message}");
                return new List<UpcomingTaskDto>();
            }
        }

        private string FormatDueDate(DateTime dueDate)
        {
            var days = (dueDate.Date - DateTime.Now.Date).Days;

            if (days == 0)
                return "Due today";
            else if (days == 1)
                return "Due tomorrow";
            else
                return $"Due in {days} days";
        }

        private string GetUrgencyColor(int daysRemaining)
        {
            return daysRemaining switch
            {
                0 => "#F44336",        // Red - Today
                1 => "#FF9800",        // Orange - Tomorrow
                _ => "#2196F3"         // Blue - Later
            };
        }
    }
}

