using Jtodo.Values;
using Jtodo.ViewModels;
using System;
using System.ComponentModel;

namespace Jtodo.DTOs
{
    public class TodoItemDto : ViewModelBase, IDataErrorInfo
    {
        private ulong _id;
        private string _title;
        private string _description;
        private DateTime _startDate;
        private DateTime _dueDate;
        private Priority _priority;
        private Status _status;
        private ulong _typeId;
        private bool _isEditing;
        private string _typeName = string.Empty;

        public ulong Id
        {
            get => _id;
            set { _id = value; OnPropertyChanged(nameof(Id)); }
        }

        public string Title
        {
            get => _title;
            set { _title = value; OnPropertyChanged(nameof(Title)); }
        }

        public string Description
        {
            get => _description;
            set { _description = value; OnPropertyChanged(nameof(Description)); }
        }

        public DateTime StartDate
        {
            get => _startDate;
            set { _startDate = value; OnPropertyChanged(nameof(StartDate)); OnPropertyChanged(nameof(DueDate)); }
        }

        public DateTime DueDate
        {
            get => _dueDate;
            set { _dueDate = value; OnPropertyChanged(nameof(DueDate)); OnPropertyChanged(nameof(StartDate)); }
        }

        public Priority Priority
        {
            get => _priority;
            set { _priority = value; OnPropertyChanged(nameof(Priority)); }
        }

        public Status Status
        {
            get => _status;
            set { _status = value; OnPropertyChanged(nameof(Status)); }
        }

        public ulong TypeId
        {
            get => _typeId;
            set { _typeId = value; OnPropertyChanged(nameof(TypeId)); }
        }

        public bool IsEditing
        {
            get => _isEditing;
            set { _isEditing = value; OnPropertyChanged(nameof(IsEditing)); }
        }

        // For display purposes - will be populated by ViewModel
        public string TypeName
        {
            get => _typeName;
            set { _typeName = value; OnPropertyChanged(nameof(TypeName)); }
        }

        public TodoItemDto()
        {
            _title = string.Empty;
            _description = string.Empty;
            _startDate = DateTime.Now;
            _dueDate = DateTime.Now.AddDays(7);
            _priority = Priority.Low;
            _status = Status.Pending;
        }

        public TodoItemDto(string title, string description, ulong typeId)
        {
            _id = 0;  // Auto-generated by database
            _title = title;
            _description = description;
            _startDate = DateTime.Now;
            _dueDate = DateTime.Now.AddDays(7);
            _priority = Priority.Low;
            _status = Status.Pending;
            _typeId = typeId;
        }

        public TodoItemDto(string title, string description, 
            DateTime startDate, DateTime dueDate, 
            Priority priority, Status status, ulong typeId)
        {
            _id = 0; // Auto-generated by database
            _title = title;
            _description = description;
            _startDate = startDate;
            _dueDate = dueDate;
            _priority = priority;
            _status = status;
            _typeId = typeId;
        }

        public TodoItemDto(ulong id,string title, string description,
            DateTime startDate, DateTime dueDate,
            Priority priority, Status status, ulong typeId)
        {
            _id = id;
            _title = title;
            _description = description;
            _startDate = startDate;
            _dueDate = dueDate;
            _priority = priority;
            _status = status;
            _typeId = typeId;
        }

        // IDataErrorInfo implementation
        public string Error => string.Empty;

        public string this[string columnName]
        {
            get
            {
                string error = string.Empty;

                switch (columnName)
                {
                    case nameof(Title):
                        if (string.IsNullOrWhiteSpace(Title))
                            error = "Title cannot be empty";
                        break;

                    case nameof(DueDate):
                        if (DueDate < StartDate)
                            error = "Due date cannot be before start date";
                        break;

                    case nameof(StartDate):
                        if (StartDate > DueDate)
                            error = "Start date cannot be after due date";
                        break;
                }

                return error;
            }
        }
    }
}
