using Jtodo.Values;
using System;

namespace Jtodo.DTOs
{
    public class TodoItemDto
    {
        public ulong Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public DateTime StartDate { get; set; }
        public DateTime DueDate { get; set; }
        public Priority Priority { get; set; }
        public Status Status { get; set; }
        public ulong TypeId { get; set; }

        public TodoItemDto()
        {
            Title = string.Empty;
            Description = string.Empty;
            StartDate = DateTime.Now;
            DueDate = DateTime.Now.AddDays(7);
            Priority = Priority.Low;
            Status = Status.Pending;
        }

        public TodoItemDto(string title, string description, ulong typeId)
        {
            Id = 0;  // Auto-generated by database
            Title = title;
            Description = description;
            StartDate = DateTime.Now;
            DueDate = DateTime.Now.AddDays(7);
            Priority = Priority.Low;
            Status = Status.Pending;
            TypeId = typeId;
        }

        public TodoItemDto(string title, string description, 
            DateTime startDate, DateTime dueDate, 
            Priority priority, Status status, ulong typeId)
        {
            Id = 0; // Auto-generated by database
            Title = title;
            Description = description;
            StartDate = startDate;
            DueDate = dueDate;
            Priority = priority;
            Status = status;
            TypeId = typeId;
        }

        public TodoItemDto(ulong id,string title, string description,
            DateTime startDate, DateTime dueDate,
            Priority priority, Status status, ulong typeId)
        {
            Id = id;
            Title = title;
            Description = description;
            StartDate = startDate;
            DueDate = dueDate;
            Priority = priority;
            Status = status;
            TypeId = typeId;
        }
    }
}
